In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("data/diabetes.csv")
print(df.shape)
df.head()

(768, 9)


Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [3]:
df["Outcome"].value_counts()

0    500
1    268
Name: Outcome, dtype: int64

In [4]:
df.isna().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [5]:
X = df.drop("Outcome", axis=1)
X

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  
0                       0.627   50  
1                       0.351   31  
2                       0.672   32  
3                       0.167   21  
4                       2.288   33  
..                        ...  ...  
763                     0.171   63  
764                     0.340   27  
765                     0.245   30  
766                     0.349   47  
767                     0.315   23  

[768 rows x 8 columns]

In [6]:
y = df["Outcome"]
y

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

In [7]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [8]:
X = scaler.fit_transform(X)
X

array([[ 0.63994726,  0.84832379,  0.14964075, ...,  0.20401277,
         0.46849198,  1.4259954 ],
       [-0.84488505, -1.12339636, -0.16054575, ..., -0.68442195,
        -0.36506078, -0.19067191],
       [ 1.23388019,  1.94372388, -0.26394125, ..., -1.10325546,
         0.60439732, -0.10558415],
       ...,
       [ 0.3429808 ,  0.00330087,  0.14964075, ..., -0.73518964,
        -0.68519336, -0.27575966],
       [-0.84488505,  0.1597866 , -0.47073225, ..., -0.24020459,
        -0.37110101,  1.17073215],
       [-0.84488505, -0.8730192 ,  0.04624525, ..., -0.20212881,
        -0.47378505, -0.87137393]])

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
X_train , X_test , y_train , y_test = train_test_split(X , y ,test_size=0.2)

In [11]:
X_train.shape , X_test.shape

((614, 8), (154, 8))

In [12]:
y_train.shape , y_test.shape

((614,), (154,))

In [13]:
from sklearn.svm import SVC , LinearSVC
from sklearn.multiclass import OneVsOneClassifier , OneVsRestClassifier
from sklearn.metrics import confusion_matrix , accuracy_score, classification_report

In [14]:
linear_oneVSrest = OneVsRestClassifier(LinearSVC(max_iter=10000))
linear_oneVSone = OneVsOneClassifier(LinearSVC())

In [15]:
linear_oneVSrest.fit(X_train,y_train)
y_pred_train_oneVSrest = linear_oneVSrest.predict(X_train)
y_pred_test_oneVSrest = linear_oneVSrest.predict(X_test)
accuracy_oneVSrest_train = accuracy_score(y_train,y_pred_train_oneVSrest)
accuracy_oneVSrest_tset = accuracy_score(y_test,y_pred_test_oneVSrest)

In [16]:
accuracy_oneVSrest_train , accuracy_oneVSrest_tset

(0.7654723127035831, 0.8181818181818182)

In [17]:
linear_oneVSone.fit(X_train,y_train)
y_pred_train_oneVSone = linear_oneVSone.predict(X_train)
y_pred_test_oneVSone = linear_oneVSone.predict(X_test)
accuracy_oneVSone_train = accuracy_score(y_train,y_pred_train_oneVSone)
accuracy_oneVSone_tset = accuracy_score(y_test,y_pred_test_oneVSone)

C:\Users\Arya.tf\anaconda3\lib\site-packages\sklearn\svm\_base.py:1206: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


In [18]:
accuracy_oneVSone_train , accuracy_oneVSone_tset

(0.7654723127035831, 0.8181818181818182)

In [19]:
confusion_matrix_linear_oneVSone = confusion_matrix(y_test , y_pred_test_oneVSone)
confusion_matrix_linear_oneVSone

array([[97,  9],
       [19, 29]], dtype=int64)

In [20]:
confusion_matrix_linear_oneVSrest = confusion_matrix(y_test , y_pred_test_oneVSrest)
confusion_matrix_linear_oneVSrest

array([[97,  9],
       [19, 29]], dtype=int64)

In [21]:
kernels = ['linear', 'poly', 'rbf', 'sigmoid']
for i in kernels:
    SVC_oneVSrest = OneVsRestClassifier(SVC(kernel=i))
    SVC_oneVSrest.fit(X_train,y_train)
    y_pred_oneVSrest = SVC_oneVSrest.predict(X_test)
    accuracy_oneVSrest = accuracy_score(y_test,y_pred_oneVSrest)    
    SVC_oneVSone = OneVsOneClassifier(SVC(kernel=i))
    SVC_oneVSone.fit(X_train,y_train)
    y_pred_oneVSone = linear_oneVSone.predict(X_test)
    accuracy_oneVSone = accuracy_score(y_test,y_pred_oneVSone)
    print(f"with {i} kernel oneVSrest accuracy is : {accuracy_oneVSrest}")
    print(f"with {i} kernel oneVSone accuracy is : {accuracy_oneVSrest}")    

with linear kernel oneVSrest accuracy is : 0.8116883116883117
with linear kernel oneVSone accuracy is : 0.8116883116883117
with poly kernel oneVSrest accuracy is : 0.7597402597402597
with poly kernel oneVSone accuracy is : 0.7597402597402597
with rbf kernel oneVSrest accuracy is : 0.7727272727272727
with rbf kernel oneVSone accuracy is : 0.7727272727272727
with sigmoid kernel oneVSrest accuracy is : 0.7012987012987013
with sigmoid kernel oneVSone accuracy is : 0.7012987012987013
